In [ ]:
from google.colab import drive
drive.mount("/content/drive")



Mounted at /content/drive



# **PRE-PROCESSING**

In [ ]:
############################################################# PREPROCESSING

import numpy as np 
import pandas as pd 
import nltk
import string

from nltk.corpus import stopwords
nltk.download('stopwords')
stop = stopwords.words('english')

def remove_stopwords(text) :
  arr_of_words=text.split()
  return_text=''
  for word in arr_of_words :
    if word not in stop :
      return_text+=word
      return_text+=' '
  return return_text

def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

def make_lower(text) :
  lower_text=text.lower()
  return lower_text

def remove_numbers(text) :
  alpha_text=''
  arr_of_words=text.split()
  for i in arr_of_words :
    try :
      x=int(i)
    except ValueError :
      alpha_text+=i
      alpha_text+=' '
  return alpha_text

def deal_media(text) :
  arr_of_words=text.split()
  final_text=''
  for i in arr_of_words :
    if 'http://' in i :
      word='aszxdcfvgb'
    else :
      word=i
    final_text+=word
    final_text+=' '
  return final_text

def remove_nan(text) :
  text = text.replace(' nan ', '')
  return text



train_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/ML_Project/ML_data/train.csv") 
test_df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/ML_Project/ML_data/test.csv")

#train_df = pd.read_csv("/content/drive/My Drive/ML_data/train.csv") 
#test_df = pd.read_csv("/content/drive/My Drive/ML_data/test.csv")

#adding location to text
train_df["text"] = train_df["text"] + ' ' + train_df["location"].astype(str) +' '
test_df["text"] = test_df["text"] + ' ' + test_df["location"].astype(str) +' '


train_df["text"] = train_df["text"].apply(remove_nan)
train_df["text"] = train_df["text"].apply(deal_media)
train_df["text"] = train_df["text"].apply(remove_stopwords)
train_df["text"] = train_df["text"].apply(remove_punctuations)
train_df["text"] = train_df["text"].apply(make_lower)
train_df["text"] = train_df["text"].apply(remove_numbers)

test_df["text"] = test_df["text"].apply(remove_nan)
test_df["text"] = test_df["text"].apply(deal_media)
test_df["text"] = test_df["text"].apply(remove_stopwords)
test_df["text"] = test_df["text"].apply(remove_punctuations)
test_df["text"] = test_df["text"].apply(make_lower)
test_df["text"] = test_df["text"].apply(remove_numbers)


x_train=train_df["text"]
y_train=train_df["target"]
x_test=test_df["text"]


print("Preprocessing done")
print("")
print("Locations added to text")
print("Links were removed")
print("Stopwords removed")
print("punctuations removed")
print("Numbers removed")
print("Lowered the text")


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
Preprocessing done

Locations added to text
Links were removed
Stopwords removed
punctuations removed
Numbers removed
Lowered the text



# **VECTORIZATION**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

cv = CountVectorizer()
tv = TfidfVectorizer()

x_traincv = cv.fit_transform(x_train)
x_traintv = tv.fit_transform(x_train)

x_testcv = cv.transform(x_test)
x_testtv = tv.transform(x_test)

print("x train and x test are formed ")



x train and x test are formed 


# **BASIC TECHNIQUES**

In [ ]:
######################################################### Basic Techniques

from sklearn.naive_bayes import MultinomialNB
from sklearn import svm
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import GridSearchCV


# Hyperparameter tuning for Naive Bayes Classifier
mnb=MultinomialNB()
list_of_parameters=[]
i=2
while i<=4 :
  i+=0.025
  i=round(i,3)
  list_of_parameters.append(i)
params={'alpha':list_of_parameters}
gs=GridSearchCV(estimator=mnb, param_grid=params, cv=5)
gs = gs.fit(x_traincv, y_train)
best_params=gs.best_params_
accuracy=gs.best_score_
print("For Naive Bayes Classifier (Count Vectorizer) :")
print("Best hyperparameter :", best_params)
print('Accuracy of train data :', accuracy)
gs = gs.fit(x_traintv, y_train)
best_params=gs.best_params_
accuracy=gs.best_score_
print("For Naive Bayes Classifier (Tfid Vectorizer):")
print("Best hyperparameter :", best_params)
print('Accuracy of train data :', accuracy)
print("")



# Hyperparameter tuning for Ridge Classifier
clf = RidgeClassifier()
list_of_parameters_for_alpha=[]
list_of_parameters_for_tol=[]
i=3
list_of_parameters_for_alpha.append(i)
while i<=5 :
  i+=0.025
  i=round(i,3)
  list_of_parameters_for_alpha.append(i)
i=0
while i<=0.0045 :
  i+=0.0005
  i=round(i,4)
  list_of_parameters_for_tol.append(i)
params={'alpha':list_of_parameters_for_alpha, 'tol':list_of_parameters_for_tol}
gs=GridSearchCV(estimator=clf, param_grid=params, cv=5)
gs = gs.fit(x_traincv, y_train)
best_params=gs.best_params_
accuracy=gs.best_score_
print("")
print("For Ridge Classifier (Count Vectorizer):")
print("Best hyperparameter :", best_params)
print('Accuracy of train data :', accuracy)
gs = gs.fit(x_traintv, y_train)
best_params=gs.best_params_
accuracy=gs.best_score_
print("For Ridge Classifier (Tfid Vectorizer):")
print("Best hyperparameter :", best_params)
print('Accuracy of train data :', accuracy)
print("")




# Hyperparameter tuning for SVM
clf = svm.SVC()
list_of_parameters_for_C=[]
list_of_parameters_for_tol=[]
i=0
while i<=2 :
  i+=1
  list_of_parameters_for_C.append(i)
list_of_parameters_for_kernel=["linear", "rbf", "sigmoid"]
i=0
while i<=0.0045 :
  i+=0.0015
  i=round(i,4)
  list_of_parameters_for_tol.append(i)
params={'C':list_of_parameters_for_C, 'kernel':list_of_parameters_for_kernel, 'tol':list_of_parameters_for_tol}
gs=GridSearchCV(estimator=clf, param_grid=params, cv=5)
gs = gs.fit(x_traincv, y_train)
best_params=gs.best_params_
accuracy=gs.best_score_
print("")
print("For SVM (Count Vectorizer):")
print("Best hyperparameter :", best_params)
print('Accuracy of train data :', accuracy)
gs = gs.fit(x_traintv, y_train)
best_params=gs.best_params_
accuracy=gs.best_score_
print("For SVM (Tfid Vectorizer):")
print("Best hyperparameter :", best_params)
print('Accuracy of train data :', accuracy)



For Naive Bayes Classifier (Count Vectorizer) :
Best hyperparameter : {'alpha': 3.875}
Accuracy of train data : 0.7107626986297706
For Naive Bayes Classifier (Tfid Vectorizer):
Best hyperparameter : {'alpha': 2.025}
Accuracy of train data : 0.724555070176695


For Ridge Classifier (Count Vectorizer):
Best hyperparameter : {'alpha': 5.025, 'tol': 0.0025}
Accuracy of train data : 0.6873843294624777
For Ridge Classifier (Tfid Vectorizer):
Best hyperparameter : {'alpha': 4.25, 'tol': 0.001}
Accuracy of train data : 0.7133917686149216


For SVM (Count Vectorizer):
Best hyperparameter : {'C': 1, 'kernel': 'rbf', 'tol': 0.0015}
Accuracy of train data : 0.7196959800794304
For SVM (Tfid Vectorizer):
Best hyperparameter : {'C': 1, 'kernel': 'sigmoid', 'tol': 0.006}
Accuracy of train data : 0.708928794834871


# **ACCURACY METRICS**

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import svm
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix


#Naive Bayes
print("Naive Bayes Classifier :")
mnb=MultinomialNB(alpha=3.875)
y_pred = cross_val_predict(mnb, x_traintv, y_train, cv=5)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy :", accuracy)
f1 = f1_score(y_train, y_pred)
print("F1 Score :", f1)
conf_mat = confusion_matrix(y_train, y_pred)
print("Confusion Matrix :")
print(conf_mat)
print("")


#SVM
print("SVM :")
clf = svm.SVC(C=1, kernel='rbf', tol=0.0015)
y_pred = cross_val_predict(clf, x_traincv, y_train, cv=5)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy :", accuracy)
f1 = f1_score(y_train, y_pred)
print("F1 Score :", f1)
conf_mat = confusion_matrix(y_train, y_pred)
print("Confusion Matrix :")
print(conf_mat)
print("")


#Ridge Classifier
print("Ridge Classifier :")
clf = RidgeClassifier(alpha=4.25, tol= 0.001)
y_pred = cross_val_predict(clf, x_traintv, y_train, cv=5)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy :", accuracy)
f1 = f1_score(y_train, y_pred)
print("F1 Score :", f1)
conf_mat = confusion_matrix(y_train, y_pred)
print("Confusion Matrix :")
print(conf_mat)

Naive Bayes Classifier :
Accuracy : 0.7120714567187705
F1 Score : 0.5497124075595727
Confusion Matrix :
[[4083  259]
 [1933 1338]]

SVM :
Accuracy : 0.7196900039406279
F1 Score : 0.5961392884178652
Confusion Matrix :
[[3904  438]
 [1696 1575]]

Ridge Classifier :
Accuracy : 0.7133849993432287
F1 Score : 0.5829510703363915
Confusion Matrix :
[[3906  436]
 [1746 1525]]


# **Submission File**

In [ ]:
'''
x_test=test_df["text"]
x_testcv=cv.transform(x_test)
mnb.fit(x_traincv, y_train)
y_pred=list(mnb.predict(x_testcv))
id_arr=list(test_df["id"])
target_arr=y_pred
df = pd.DataFrame(list(zip(id_arr, target_arr)),columns =['id', 'target'])
df.to_csv(r'/content/drive/My Drive/ML_data/submission_file.csv', index=False)
'''